name: Lint Code Base

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run PyLint
        run: |
          pylint flathunter/ --rcfile=.pylintrc --output-format=text --reports=no