name: Lint Code Base

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt1-dev
      
      - name: Install pylint and essential dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint==2.12.2 astroid==2.9.3
          # Install only essential dependencies for linting
          pip install beautifulsoup4 requests PyYAML selenium aiohttp flask
          # Try to install other dependencies, but don't fail if they can't be installed
          pip install -r requirements.txt || echo "Some dependencies failed to install, but continuing with linting"
      
      - name: Run PyLint
        run: |
          pylint flathunter/ --output-format=text --reports=no --fail-under=9.5