name: Lint Code Base

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt || echo "No requirements.txt found"
      
      - name: Run PyLint
        run: |
          pylint flathunter/ --output-format=text --reports=no